- id: alert_when_front_door_open
  alias: 'Alert when front door is open and nobody home'
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_contact
    from: 'off'
    to: 'on'
  condition:
      condition: state
      entity_id: sensor.anyone_home
      state: 'not_home'
  action:
    - if:
      - condition: state
        entity_id: sensor.anyone_home
        state: not_home
      then:
        - service: notify.mobile_app_jeffsphone
          data_template:
            title: "Alarm Panel"
            message: "Front door open"
      else:
        - service: media_player.play_media
          target:
            entity_id: media_player.kitchen_display
          data:
            media_content_id: media-source://tts/google_translate?message=Front+Door+Open
            media_content_type: provider