binary_sensor:
  - platform: group
    name: "Entry Points"
    unique_id: a79ca463-dfe5-47b0-8928-11a5e2e448a4
    device_class: opening
    entities:
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_front_door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_sliding_door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_garage_door
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_kitchen_left_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_kitchen_right_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_dining_room_left_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_dining_room_right_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_living_room_left_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_dining_room_right_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_guest_bedroom_left_window
      - binary_sensor.lumi_lumi_sensor_magnet_aq2_guest_bedroom_right_window  

lock:
  - platform: group
    name: "Locks"
    unique_id: 796d1c9b-55d0-42b1-aa46-f7d5a19b38dd
    entities:
      - lock.front_door

automation:
  - id: alert_when_door_window_open
    alias: 'Alert When a Door or Window is Open'
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_front_door
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_sliding_door
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_garage_door
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_dining_room_left_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_dining_room_right_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_living_room_left_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_living_room_right_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_guest_bedroom_left_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_guest_bedroom_right_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_kitchen_left_window
        - binary_sensor.lumi_lumi_sensor_magnet_aq2_kitchen_right_window
      from: 'off'
      to: 'on'
    action:
      - if:
        - condition: state
          entity_id: sensor.anyone_home
          state: not_home
        then:
          - service: script.notify_engine
            data_template:
              title: "Alarm Panel"
              value1: >-
                {{ trigger.to_state.attributes.friendly_name }} Open
              who: family
              importance_id: high
              color: red
        else:
          - service: tts.google_say
            data_template:
              entity_id: media_player.kitchen_display
              message: >-
                {{ trigger.to_state.attributes.friendly_name }}, Open
