homeassistant:
  customize_glob: 
    "binary_sensor.*_window_contact":
      device_class: window

binary_sensor:
  - platform: group
    name: "Entry Points"
    unique_id: a79ca463-dfe5-47b0-8928-11a5e2e448a4
    device_class: opening
    entities:
      - binary_sensor.front_door_contact
      - binary_sensor.sliding_door_contact
      - binary_sensor.garage_access_door_contact
      - binary_sensor.garage_door_contact
      - binary_sensor.garage_left_window_contact
      - binary_sensor.garage_right_window_contact
      - binary_sensor.kitchen_left_window_contact
      - binary_sensor.kitchen_right_window_contact
      - binary_sensor.dining_room_left_window_contact
      - binary_sensor.dining_room_right_window_contact
      - binary_sensor.living_room_left_window_contact
      - binary_sensor.dining_room_right_window_contact
      - binary_sensor.guest_bedroom_left_window_contact
      - binary_sensor.guest_bedroom_right_window_contact

lock:
  - platform: group
    name: "Locks"
    unique_id: 796d1c9b-55d0-42b1-aa46-f7d5a19b38dd
    entities:
      - lock.front_door

automation:
  - id: alert_when_door_window_open
    alias: 'Alert When a Door or Window is Open'
    initial_state: on
    trigger:
      platform: state
      entity_id:
        - binary_sensor.front_door_contact
        - binary_sensor.sliding_door_contact
        - binary_sensor.garage_access_door_contact
        - binary_sensor.garage_door_contact
        - binary_sensor.garage_left_window_contact
        - binary_sensor.garage_right_window_contact
        - binary_sensor.dining_room_left_window_contact
        - binary_sensor.dining_room_right_window_contact
        - binary_sensor.living_room_left_window_contact
        - binary_sensor.living_room_right_window_contact
        - binary_sensor.guest_bedroom_left_window_contact
        - binary_sensor.guest_bedroom_right_window_contact
        - binary_sensor.kitchen_left_window_contact
        - binary_sensor.kitchen_right_window_contact

      from: 'off'
      to: 'on'
    action:
      - if:
        - condition: state
          entity_id: sensor.anyone_home
          state: not_home
        then:
          - service: script.notify_engine
            data_template:
              title: "Alarm Panel"
              value1: >-
                {{ trigger.to_state.attributes.friendly_name | replace(" contact","") }} Open
              who: family
              importance_id: high
              color: red
        else:
          - service: tts.speak
            data_template:
              media_player_entity_id: media_player.kitchen_display
              message: >-
                {{ trigger.to_state.attributes.friendly_name | replace(" contact","") }}, Open
            target:
              entity_id: tts.piper
