automation:
  - id: 1c1b004d-7012-47cb-b9f9-3e81776ba688
    alias: "Back Porch Audio Remote"
    description: "back porch audio remote"
    mode: single
    trigger:
      - platform: state
        entity_id: button.back_porch_audio_pico_on
        id: play
      - platform: state
        entity_id: button.back_porch_audio_pico_off
        id: next
      - platform: state
        entity_id: button.back_porch_audio_pico_raise
        id: volume_up
      - platform: state
        entity_id: button.back_porch_audio_pico_lower
        id: volume_down
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: play
            sequence:
              - service: media_player.media_play_pause
                data: {}
                target:
                  entity_id: media_player.backyard
          - conditions:
              - condition: trigger
                id: next
            sequence:
              - service: media_player.media_next_track
                data: {}
                target:
                  entity_id: media_player.backyard
          - conditions:
              - condition: trigger
                id: volume_up
            sequence:
              - service: media_player.volume_up
                data: {}
                target:
                  entity_id: media_player.backyard
          - conditions:
              - condition: trigger
                id: volume_down
            sequence:
              - service: media_player.volume_down
                data: {}
                target:
                  entity_id: media_player.backyard
