automation:
  - id: c5aea99d-842d-4d05-973d-99251104e502
    alias: "Back Porch Audio Remote"
    description: "back porch audio remote"
    mode: single
    trigger:
      - platform: device
        device_id: 0a648e823459f3188edc9c9f2d1ca021
        domain: lutron_caseta
        type: press
        subtype: "on"
        id: play
      - platform: device
        device_id: 0a648e823459f3188edc9c9f2d1ca021
        domain: lutron_caseta
        type: press
        subtype: "off"
        id: next
      - platform: device
        device_id: 0a648e823459f3188edc9c9f2d1ca021
        domain: lutron_caseta
        type: press
        subtype: "raise"
        id: volume_up
      - platform: device
        device_id: 0a648e823459f3188edc9c9f2d1ca021
        domain: lutron_caseta
        type: press
        subtype: "lower"
        id: volume_down
      - platform: device
        device_id: 0a648e823459f3188edc9c9f2d1ca021
        domain: lutron_caseta
        type: press
        subtype: "stop"
        id: favorite

    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: play
            sequence:
              - service: media_player.media_play_pause
                data: {}
                target:
                  entity_id: media_player.backyard_speakers
          - conditions:
              - condition: trigger
                id: next
            sequence:
              - service: media_player.media_next_track
                data: {}
                target:
                  entity_id: media_player.backyard_speakers
          - conditions:
              - condition: trigger
                id: volume_up
            sequence:
              - service: media_player.volume_up
                data: {}
                target:
                  entity_id: media_player.backyard_speakers
          - conditions:
              - condition: trigger
                id: volume_down
            sequence:
              - service: media_player.volume_down
                data: {}
                target:
                  entity_id: media_player.backyard_speakers
