input_boolean:
  good_night:
    name: good_night
    icon: mdi:weather-night
    initial: off

automation:
  - alias: 'Good Night Trigger'
    id: 26846f7b-bc76-43d2-99be-af552da7700f
    trigger:
      - platform: state
        entity_id: input_boolean.good_night
        from: 'off'
        to: 'on'
      - platform: state
        entity_id:
          - binary_sensor.jeff_bed_sensor
          - binary_sensor.sara_bed_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.jeff_bed_sensor
            state: 'on'
          - condition: state
            entity_id: person.jeff
            state: 'not_home'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.sara_bed_sensor
            state: 'on'
          - condition: state
            entity_id: person.sara
            state: 'not_home'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.good_night
      - service: homeassistant.turn_off
        target:
          entity_id:
            - light.interior_lights
            - light.exterior_lights
            - switch.living_room_outlet
      - service: fan.set_percentage
        data:
          percentage: 50
        target:
          area_id: master_bedroom
      - service: fan.turn_on
        data:
          entity_id: fan.master_bedroom_ceiling_fan
      - service: lock.lock
        data:
          entity_id: lock.front_door
      - service: media_player.volume_set
        data:
          entity_id: media_player.master_bedroom_assistant
          volume_level: '0.20'
      - service: media_player.play_media
        data:
          media_content_id: https://www.gstatic.com/voice_delight/sounds/long/ocean.mp3
          media_content_type: audio/mp3
        target:
          entity_id: media_player.master_bedroom_assistant
