light:
  - platform: group
    name: Interior Lights
    unique_id: 2cd18f95-f3dd-4243-ae0a-598afc437a5c
    entities:
      - light.upstairs_lights
      - light.downstairs_lights
  - platform: group
    name: Upstairs Lights
    unique_id: 5ac09b55-febe-4c9f-93b3-8d7205270b97
    entities:
      - light.game_room_main_lights
      - light.master_bedroom_main_lights
      - light.nursery_main_lights
      - light.office_main_lights
      - light.upstairs_hallway_main_lights
  - platform: group
    name: Downstairs Lights
    unique_id: 0430b6cc-539f-4023-bca9-c0ce8782b8d2
    entities:
      - light.dining_room_chandelier
      - light.front_foyer_chandelier
      - light.garage_main_lights
      - light.guest_bedroom_main_lights
      - light.kitchen_lights
      - light.living_room_main_lights
  - platform: group
    name: Front Exterior Lights
    unique_id: 556661fe-04ab-4c4e-b7b3-2ff93a306f55
    entities:
      - light.front_porch_main_lights
      - light.front_porch_door_lights
      - light.exterior_landscape_lights
  - platform: group
    name: Back Exterior Lights
    unique_id: a44bb8f2-fea2-4a61-bba1-d9c7a38985b3
    entities:
      - light.back_porch_main_lights
      - light.backyard_floodlights
      - light.pool_lights
  - platform: group
    name: Exterior Lights
    unique_id: 6de36a80-3994-4dbc-97bd-473774eb13f7
    entities:
      - light.front_exterior_lights
      - light.back_exterior_lights
  - platform: group
    name: Kitchen Lights
    unique_id: 253276d0-7733-45e0-a452-f3f713d42687
    entities:
      - light.kitchen_island_pendants
      - light.kitchen_main_lights
      - light.kitchen_under_cabinet
  - platform: group
    name: Office Lamp
    entities:
      - light.office_lamp_top
      - light.office_lamp_bottom
automation:
  - id: 8492848d-48ef84-8593ae-ace748-83848295ea730
    alias: "Master Bedroom Closet Motion Light"
    description: ""
    use_blueprint:
      path: homeassistant/motion_light.yaml
      input:
        motion_entity: binary_sensor.master_bedroom_closet_motion_sensor_occupancy
          light_target:
            entity_id: light.master_bedroom_closet_light
